name: Deploy stuff!

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
    hello_world_dev:
        name: 'Say hello world from dev'
        environment: dev
        runs-on: ubuntu-latest
        steps:
            - name: 'Someone approved DEV'
              run: echo Approed for DEV
    hello_world_pat:
        name: 'Say hello world from pat'
        environment: pat
        runs-on: ubuntu-latest
        steps:
            - name: 'Someone approved PAT'
              run: echo Approed for PAT
    