name: Example of cURL action

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
    hello_world_dev:
        name: 'Perform REST API'
        environment: dev
        runs-on: [self-hosted, linux, x64]
        steps:
            - name: 'Someone approved DEV'
              run: echo Approed for DEV
    hello_world_pat:
        name: 'Perform REST API'
        environment: pat
        runs-on: [self-hosted, linux, x64]
        steps:
            - name: 'Someone approved PAT'
              run: echo Approed for PAT
    